--- 
abstract: Read National Financial Service's Account Balance file into data structures
author: Guillermo Roditi (groditi) <groditi@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Finance-NFS-File-AccountBalance
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0
  IO::File: 0
  Moose: 0.28
version: 0.001000
